[project]
name = "greek-ocr"
version = "0.1.0"
description = "We are going to digitize the whole Greek Legal manuscripts"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bitsandbytes>=0.48.2",
    "chardet>=5.2.0",
    "huggingface-hub>=0.36.0",
    "matplotlib>=3.10.7",
    "psutil>=7.1.3",
    "qwen-vl-utils>=0.0.14",
    "setuptools>=80.9.0",
    "torch>=2.9.1",
    "torchvision>=0.24.1",
    "transformers>=4.57.1",
    "unsloth>=2024.8",
]
